### summary
- numpy : 선형대수를 빠르게 연산해주는 패키지
- 행렬의 생성 1 : ndarray, np.array(iterable)
- 행렬의 생성 2 : ones, zeros
- 행렬 데이터의 선택 : array[x, y, z]
- 행렬 데이터 수정
    - 행렬 데이터를 선택
    - =, > (값(scalar, vector, matrix))
    - 브로드캐스팅 개념
- arange : list에서 사용하는 range와 유사 : 결과가 ndarray 데이터 타입

### quiz
- 100 - 130까지 랜덤한 숫자를 가지는 8x8 행렬을 만들고,
- 3의 배수는 fiz, 5의 배수는 buz, 3과 5의 배수는 fbz 문자로 변환
- 위의 조건에 맞지 않는 데이터는 랜덤하게 생성된 정수로 출력
- 랜덤한 행렬 데이터
```
data = np.random.randint(100, 130, (8, 8))
```
- 데이터 타입이 정수 -> 문자열 : ndarray.astype()

In [2]:
import numpy as np

In [49]:
data = np.random.randint(100, 130, size=(8,8))
data

array([[126, 111, 114, 125, 126, 114, 100, 127],
       [110, 111, 104, 111, 121, 103, 114, 100],
       [102, 100, 123, 104, 129, 124, 112, 116],
       [118, 100, 109, 107, 105, 102, 104, 128],
       [111, 106, 117, 108, 108, 125, 104, 109],
       [118, 101, 118, 100, 102, 129, 113, 102],
       [115, 104, 117, 116, 106, 103, 107, 100],
       [123, 102, 119, 110, 110, 107, 102, 102]])

In [85]:
# Remember :
data1 = np.array([1, 2, 3])
data2 = [True, False, True]
data1[data2]

array([1, 3])

In [86]:
# 3의 배수, 5의 배수, 15의 배수 위치값에 대한 T/F matrix 생성
idx_3 = (data % 3 == 0)
idx_3

array([[ True,  True,  True, False,  True,  True, False, False],
       [False,  True, False,  True, False, False,  True, False],
       [ True, False,  True, False,  True, False, False, False],
       [False, False, False, False,  True,  True, False, False],
       [ True, False,  True,  True,  True, False, False, False],
       [False, False, False, False,  True,  True, False,  True],
       [False, False,  True, False, False, False, False, False],
       [ True,  True, False, False, False, False,  True,  True]])

In [87]:
idx_5 = (data % 5 == 0)
idx_5

array([[False, False, False,  True, False, False,  True, False],
       [ True, False, False, False, False, False, False,  True],
       [False,  True, False, False, False, False, False, False],
       [False,  True, False, False,  True, False, False, False],
       [False, False, False, False, False,  True, False, False],
       [False, False, False,  True, False, False, False, False],
       [ True, False, False, False, False, False, False,  True],
       [False, False, False,  True,  True, False, False, False]])

In [94]:
idx_15 = (data % 15 == 0)
idx_15

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [90]:
# 데이터 타입을 str으로 변환
data_str = data.astype("str")
data_str

array([['126', '111', '114', '125', '126', '114', '100', '127'],
       ['110', '111', '104', '111', '121', '103', '114', '100'],
       ['102', '100', '123', '104', '129', '124', '112', '116'],
       ['118', '100', '109', '107', '105', '102', '104', '128'],
       ['111', '106', '117', '108', '108', '125', '104', '109'],
       ['118', '101', '118', '100', '102', '129', '113', '102'],
       ['115', '104', '117', '116', '106', '103', '107', '100'],
       ['123', '102', '119', '110', '110', '107', '102', '102']],
      dtype='<U11')

In [92]:
# T/F matrix를 이용하여 특정 조건의 데이터를 선택 후 브로드캐스팅하게 값을 대입
data_str[idx_3] = "fiz"
data_str[idx_5] = "buz"
data_str[idx_15] = "fbz"
data_str

array([['fiz', 'fiz', 'fiz', 'buz', 'fiz', 'fiz', 'buz', '127'],
       ['buz', 'fiz', '104', 'fiz', '121', '103', 'fiz', 'buz'],
       ['fiz', 'buz', 'fiz', '104', 'fiz', '124', '112', '116'],
       ['118', 'buz', '109', '107', 'fbz', 'fiz', '104', '128'],
       ['fiz', '106', 'fiz', 'fiz', 'fiz', 'buz', '104', '109'],
       ['118', '101', '118', 'buz', 'fiz', 'fiz', '113', 'fiz'],
       ['buz', '104', 'fiz', '116', '106', '103', '107', 'buz'],
       ['fiz', 'fiz', '119', 'buz', 'buz', '107', 'fiz', 'fiz']],
      dtype='<U11')

### Quiz
- 1 ~ 20까지 랜덤한 숫자를 가지는 5x5 행렬 생성
- 최대값에는 MAX, 최소값에는 MIN 문자열이 들어가도록 치환하는 코드
- 최대값과 최소값 함수 : 
```
np.min(ndarray), np.max(ndarray)
```

In [96]:
data = np.random.randint(1, 20, size=(5,5))
data

array([[ 7, 15, 18, 18,  6],
       [15, 17,  2, 12, 12],
       [17,  1, 15, 10,  2],
       [11, 12,  8, 10, 13],
       [ 2, 10, 13,  5, 19]])

In [105]:
# MAX, MIN 찾기
idx_min = (data == np.min(data))
idx_max = (data == np.max(data))

In [106]:
# str 변환
data_str = data.astype("str")
data_str

array([['7', '15', '18', '18', '6'],
       ['15', '17', '2', '12', '12'],
       ['17', '1', '15', '10', '2'],
       ['11', '12', '8', '10', '13'],
       ['2', '10', '13', '5', '19']], dtype='<U11')

In [107]:
# 브로드캐스팅 대입
data_str[idx_min] = "MIN"
data_str[idx_max] = "MAX"
data_str

array([['7', '15', '18', '18', '6'],
       ['15', '17', '2', '12', '12'],
       ['17', 'MIN', '15', '10', '2'],
       ['11', '12', '8', '10', '13'],
       ['2', '10', '13', '5', 'MAX']], dtype='<U11')

### 1. linspace, logspace
- linspace : 설정한 범위에서 선형적으로 분할한 위치값 출력
- logspace : 설정한 범위에서 로그로 분할한 위치값 출력

In [3]:
# linspace
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [4]:
# logspace
# log10(x1)=2, log10(x2)=3, log10(x3)=4
np.logspace(2, 4, 3)

array([  100.,  1000., 10000.])

In [6]:
# 30세에 연봉이 $100,000이고 60세에 연봉이 $1,000,000일 때
# 연봉이 선형으로 증가, 지수 함수로 증가하는 두 경우에서의 40세와 50세 연봉을 출력
np.linspace(100000, 1000000, 4)

array([ 100000.,  400000.,  700000., 1000000.])

In [8]:
np.logspace(np.log10(100000), np.log10(1000000), 4)

array([ 100000.        ,  215443.46900319,  464158.88336128,
       1000000.        ])

### 2. numpy random
- seed : 랜덤값의 설정값 (랜덤하게 섞이지만 동일성을 유지하기 위한 트릭)
- rand : 균등분포로 난수 발생
- randn : 정규분포로 난수 발생
- randint : 균등분포로 정수값을 발생
- shuffle : 행렬 데이터를 섞어줍니다.
- choice : 특정 확률로 데이터 선택

In [9]:
# seed
np.random.seed(1)
result1 = np.random.randint(10, 100, 10)

np.random.seed(1)
result2 = np.random.randint(10, 100, 10)

np.random.seed(2)
result3 = np.random.randint(10, 100, 10)

result1, result2, result3

(array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([47, 22, 82, 19, 85, 15, 89, 74, 26, 11]),
 array([50, 25, 82, 32, 53, 92, 85, 17, 44, 59]))

In [10]:
np.random.rand(10)

array([0.20464863, 0.61927097, 0.29965467, 0.26682728, 0.62113383,
       0.52914209, 0.13457995, 0.51357812, 0.18443987, 0.78533515])

In [11]:
np.random.randn(10)

array([-0.0191305 ,  1.17500122, -0.74787095,  0.00902525, -0.87810789,
       -0.15643417,  0.25657045, -0.98877905, -0.33882197, -0.23618403])

In [24]:
# shuffle
r = np.random.randint(1, 10, (3, 4))
r

array([[1, 8, 1, 6],
       [3, 6, 2, 4],
       [4, 2, 9, 7]])

In [26]:
np.random.shuffle(r)
r

array([[4, 2, 9, 7],
       [1, 8, 1, 6],
       [3, 6, 2, 4]])

In [31]:
# choice
np.random.choice(5, 10, p=[0.1, 0, 0.4, 0.2, 0.3])

array([4, 0, 2, 4, 0, 0, 2, 3, 0, 0])

In [33]:
# unique
numbers, counts = np.unique(r, return_counts=True)
print(numbers)
print(counts)

[1 2 3 4 6 7 8 9]
[2 2 1 2 2 1 1 1]


### 3. 행렬 데이터의 결합
- concatenate

In [34]:
na1 = np.random.randint(10, size=(2,3))
na2 = np.random.randint(10, size=(3,2))
na3 = np.random.randint(10, size=(3,3))

In [35]:
# 세로 결합
na1

array([[0, 6, 6],
       [8, 6, 9]])

In [37]:
na2

array([[5, 1],
       [5, 9],
       [4, 9]])

In [36]:
na3

array([[8, 3, 4],
       [6, 2, 4],
       [7, 5, 1]])

In [41]:
np.concatenate((na1, na3))

array([[0, 6, 6],
       [8, 6, 9],
       [8, 3, 4],
       [6, 2, 4],
       [7, 5, 1]])

In [43]:
# 가로 결합
np.concatenate((na2, na3), axis=1)

array([[5, 1, 8, 3, 4],
       [5, 9, 6, 2, 4],
       [4, 9, 7, 5, 1]])

In [44]:
# c_, r_
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [45]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [46]:
# split, var, std, mean, ...