#### 역행렬과 선형 연립방정식의 해

In [1]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [2]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [3]:
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [4]:
x = Ainv @ b
x

array([[1.],
       [1.],
       [1.]])

In [6]:
A @ x - b

array([[0.],
       [0.],
       [0.]])

In [10]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.],
       [1.],
       [1.]])

#### Ex 2.4.5

In [13]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]]    # 'CRIM', 'NOX', 'RM', 'AGE'
b = y[:4]
A, b

(array([[6.320e-03, 5.380e-01, 6.575e+00, 6.520e+01],
        [2.731e-02, 4.690e-01, 6.421e+00, 7.890e+01],
        [2.729e-02, 4.690e-01, 7.185e+00, 6.110e+01],
        [3.237e-02, 4.580e-01, 6.998e+00, 4.580e+01]]),
 array([24. , 21.6, 34.7, 33.4]))

In [14]:
w1, resid, rank, s = np.linalg.lstsq(A, b)
w1

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([-3.12710043e+02, -1.15193942e+02,  1.44996465e+01, -1.13259317e-01])

가중치 부호로부터 다음 사실을 알 수 있다. 집값은:
- 범죄율에 반비례한다
- 공기 오염도에 반비례한다
- 방의 개수에 비례한다
- 오래된 정도에 반비례한다

In [19]:
A = np.array([[1, 1, 0], [0, 1, 1], [1, 1, 1], [1, 1, 2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [20]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [21]:
Apinv = np.linalg.inv(A.T @ A) @ A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [22]:
x = Apinv @ b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [23]:
A @ x

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [28]:
x, resid, rank, s = np.linalg.lstsq(A, b)
x

C:\Anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [29]:
resid, np.linalg.norm(A @ x - b) ** 2

(array([0.00166667]), 0.0016666666666666698)

#### Ex 2.4.6

In [35]:
from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
w, resid, rank, s = np.linalg.lstsq(X, y, rcond=None)
w

array([-9.28965170e-02,  4.87149552e-02, -4.05997958e-03,  2.85399882e+00,
       -2.86843637e+00,  5.92814778e+00, -7.26933458e-03, -9.68514157e-01,
        1.71151128e-01, -9.39621540e-03, -3.92190926e-01,  1.49056102e-02,
       -4.16304471e-01])

가중치 부호로부터 다음 사실을 알 수 있다. 집값은:
1. 범죄율에 반비례한다
2. 비소매상업지역 면적 비율에 비례한다
3. 일산화질소 농도에 반비례한다
4. 주택당 방 수에 비례한다
5. 인구 중 하위 계층 비율에 반비례한다
6. 인구 중 흑인 비율에 비례한다
7. 학생/교사 비율에 반비례한다
8. 25,000 평방피트를 초과 거주지역 비율에 반비례한다.
9. 찰스강의 경계에 위치한 경우에 비례한다.
10. 1940년 이전에 건축된 주택의 비율에 반비례한다.
11. 방사형 고속도로까지의 거리에 반비례한다.
12. 보스톤 직업 센터 5곳까지의 가중평균거리에 비례한다.
13. 재산세율에 반비례한다.