#### 넘파이를 사용한 고유분해

In [4]:
A = np.array([[1, -2], [2, -3]])
w1, V1 = np.linalg.eig(A)
print(w1)
print(V1)

[-0.99999998 -1.00000002]
[[0.70710678 0.70710678]
 [0.70710678 0.70710678]]


In [5]:
B = np.array([[2, 3], [2, 1]])
w2, V2 = np.linalg.eig(B)
print(w2)
print(V2)

[ 4. -1.]
[[ 0.83205029 -0.70710678]
 [ 0.5547002   0.70710678]]


In [6]:
C = np.array([[0, -1], [1, 0]])
w3, V3 = np.linalg.eig(C)
print(w3)
print(V3)

[0.+1.j 0.-1.j]
[[0.70710678+0.j         0.70710678-0.j        ]
 [0.        -0.70710678j 0.        +0.70710678j]]


#### Ex. 3.3.5

In [7]:
D = np.array([[2, 1], [1, 2]])
w4, V4 = np.linalg.eig(D)
print(w4)
print(V4)

[3. 1.]
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [8]:
F = np.array([[1, 1], [0, 1]])
w5, V5 = np.linalg.eig(F)
print(w5)
print(V5)

[1. 1.]
[[ 1.00000000e+00 -1.00000000e+00]
 [ 0.00000000e+00  2.22044605e-16]]


#### 대각화

In [9]:
V2

array([[ 0.83205029, -0.70710678],
       [ 0.5547002 ,  0.70710678]])

In [10]:
V2_inv = np.linalg.inv(V2)
V2_inv

array([[ 0.72111026,  0.72111026],
       [-0.56568542,  0.84852814]])

In [11]:
V2 @ np.diag(w2) @ V2_inv

array([[2., 3.],
       [2., 1.]])

#### 대칭행렬을 랭크-1 행렬의 합으로 분해

In [8]:
A = np.array([[60, 30, 20], [30, 20, 15], [20, 15, 12]])
w, V = np.linalg.eig(A)
w1, w2, w3 = w
v1 = V[:, 0:1]
v2 = V[:, 1:2]
v3 = V[:, 2:3]
A1 = v1 @ v1.T
A2 = v2 @ v2.T
A3 = v3 @ v3.T

In [9]:
w

array([84.49913563,  7.33962395,  0.16124042])

In [10]:
w1 * A1

array([[57.79768857, 32.13739648, 22.59357583],
       [32.13739648, 17.8694387 , 12.56276371],
       [22.59357583, 12.56276371,  8.83200836]])

In [11]:
w2 * A2

array([[ 2.19968372, -2.12270483, -2.60775134],
       [-2.12270483,  2.04841985,  2.51649195],
       [-2.60775134,  2.51649195,  3.09152039]])

In [12]:
w3 * A3

array([[ 0.00262772, -0.01469165,  0.01417551],
       [-0.01469165,  0.08214145, -0.07925566],
       [ 0.01417551, -0.07925566,  0.07647125]])

In [13]:
w1 * A1 + w2 * A2 + w3 * A3

array([[60., 30., 20.],
       [30., 20., 15.],
       [20., 15., 12.]])

In [14]:
np.linalg.inv(A)

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

In [15]:
1 / w1 * A1

array([[0.0080948 , 0.00450097, 0.00316432],
       [0.00450097, 0.00250269, 0.00175947],
       [0.00316432, 0.00175947, 0.00123696]])

In [16]:
1 / w2 * A2

array([[ 0.04083313, -0.03940415, -0.04840816],
       [-0.03940415,  0.03802519,  0.04671409],
       [-0.04840816,  0.04671409,  0.05738845]])

In [17]:
1 / w3 * A3

array([[ 0.10107208, -0.56509682,  0.54524384],
       [-0.56509682,  3.15947213, -3.04847356],
       [ 0.54524384, -3.04847356,  2.94137459]])

In [18]:
1 / w1 * A1 + 1 / w2 * A2 + 1 / w3 * A3

array([[ 0.15, -0.6 ,  0.5 ],
       [-0.6 ,  3.2 , -3.  ],
       [ 0.5 , -3.  ,  3.  ]])

#### Ex. 3.3.9

In [22]:
from sklearn.datasets import load_iris
X = load_iris().data
w, V = np.linalg.eig(X.T @ X)
w

array([9.20830507e+03, 3.15454317e+02, 1.19780429e+01, 3.55257020e+00])

In [24]:
from sklearn.datasets import load_boston
X = load_boston().data
w, V = np.linalg.eig(X.T @ X)
w

array([1.58386796e+08, 1.18747372e+07, 4.17002244e+05, 1.61644573e+05,
       2.52697480e+04, 1.47629635e+04, 8.18396001e+03, 6.07326738e+03,
       4.23577535e+03, 6.06399504e+02, 3.27412564e+02, 3.04157837e+01,
       2.19326965e+00])